# Generated by Django 4.2.1 on 2023-06-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_nft', '0002_alter_collectionnft_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionnft',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='collectionnft',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
