# Generated by Django 4.2.1 on 2023-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_nft', '0003_rename_author_id_collectionnft_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='collectionnft',
            name='previous_prices',
            field=models.ManyToManyField(to='collections_nft.previousprice'),
        ),
    ]
