# Generated by Django 4.2.1 on 2023-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_nft', '0004_previousprice_collectionnft_previous_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionnft',
            name='previous_prices',
            field=models.ManyToManyField(blank=True, to='collections_nft.previousprice'),
        ),
    ]
