# Generated by Django 4.2.1 on 2023-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_nft', '0005_alter_collectionnft_previous_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionnft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections_nft'),
        ),
    ]
