# Generated by Django 4.2.1 on 2023-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_nft', '0006_alter_collectionnft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionnft',
            name='previous_prices',
            field=models.ManyToManyField(blank=True, related_name='previous_prices', to='collections_nft.previousprice'),
        ),
    ]
