# Generated by Django 4.2.1 on 2023-08-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_nft', '0007_alter_collectionnft_previous_prices'),
        ('nft', '0002_alter_nft_image'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='collection_nft_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_collections', to='collections_nft.collectionnft'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nft_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_nft', to='nft.nft'),
        ),
    ]
