# Generated by Django 4.2.1 on 2023-07-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cover_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_images',
            field=models.ManyToManyField(blank=True, related_name='cover_images', to='users.coverimage'),
        ),
    ]
