# Generated by Django 4.2.1 on 2023-07-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_cover_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_images',
        ),
        migrations.DeleteModel(
            name='CoverImage',
        ),
    ]
