# Generated by Django 4.2.1 on 2023-08-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_nftauction_nft_auction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='auction_price',
            new_name='auction_prices',
        ),
    ]
