# Generated by Django 4.2.1 on 2023-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_rename_auction_price_nft_auction_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='auction_prices',
        ),
        migrations.AddField(
            model_name='nft',
            name='auction_prices',
            field=models.ManyToManyField(blank=True, related_name='nft_action_price', to='nft.nftauction'),
        ),
    ]
